// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/collections": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/collections" | "/products" | "/*";
  };
  "routes/collections..tsx": {
    id: "routes/collections.";
    page: "/collections";
  };
  "routes/products..tsx": {
    id: "routes/products.";
    page: "/products";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/collections.": typeof import("./app/routes/collections..tsx");
  "routes/products.": typeof import("./app/routes/products..tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};